package contacts.entity;
// Generated Jun 6, 2018 4:55:56 PM by Hibernate Tools 4.3.1



/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String phone;

    public Contact() {
    }

    public Contact(String firstName, String lastName, String phone) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.phone = phone;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


